version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /cicd/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /cicd/docker-credentials/password
    DOCKER_REGISTRY_URL: /cicd/docker-registry/url
    SONAR_TOKEN: /cicd/sonar/sonar-token

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
      
  pre_build:
    commands:
      - echo "Installing dependencies..."
      # Uncommenting Sonar Scanner download steps
      - export SONAR_SCANNER_VERSION=4.7.0.2747
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      - export SONAR_SCANNER_OPTS="-server"

  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_USERNAME/swiggy:latest" .
      - docker push "$DOCKER_REGISTRY_USERNAME/swiggy:latest"

  post_build:
    commands:
      - echo "Running SonarQube analysis result"
      # Using the SONAR_TOKEN injected from AWS Parameter Store
      - sonar-scanner -Dsonar.projectKey=swiggy -Dsonar.sources=. -Dsonar.host.url=http://65.1.1.149:9000/ -Dsonar.login=$SONAR_TOKEN
      - "aws ses send-email --from vinitkarlekar84474@gmail.com --to vinitkarlekar84474@gmail.com --subject \"CodeBuild Status: $CODEBUILD_BUILD_ID\" --text \"Build status: $CODEBUILD_BUILD_STATUS\" --region us-east-1"

artifacts:
  files:
    - appspec.yaml