version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /cicd/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /cicd/docker-credentials/password
    DOCKER_REGISTRY_URL: /cicd/docker-registry/url
    SONAR_TOKEN: /cicd/sonar/sonar-token

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
      
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - echo "Performing Trivy file scan before building the image..."
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b .
      - ./trivy filesystem --exit-code 0 --no-progress . >> trivyfilescan.txt
      - echo "Downloading and installing OWASP Dependency-Check..."
      - wget https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.9/dependency-check-9.0.9-release.zip
      - unzip dependency-check-9.0.9-release.zip
      # Uncommenting Sonar Scanner download steps
      - export SONAR_SCANNER_VERSION=4.7.0.2747
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      - export SONAR_SCANNER_OPTS="-server"

  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_USERNAME/swiggy:latest" .
      - docker push "$DOCKER_REGISTRY_USERNAME/swiggy:latest"

  post_build:
    commands:
      - echo "Performing Trivy image scan after building the image..."
      - ./trivy image "$DOCKER_REGISTRY_USERNAME/swiggy:latest" >> trivyimage.txt
      - echo "Running OWASP Dependency-Check scan..."
      - cd dependency-check/bin
      - ./dependency-check.sh --scan ../../ --format HTML
      - cd ../../
      - echo "Running SonarQube analysis result"
      # Using the SONAR_TOKEN injected from AWS Parameter Store
      - sonar-scanner -Dsonar.projectKey=swiggy -Dsonar.sources=. -Dsonar.host.url=http://34.197.103.86:9000/ -Dsonar.login=$SONAR_TOKEN

artifacts:
  files:
    - appspec.yaml
    - trivyfilescan.txt
    - trivyimage.txt
    - dependency-check-report.html